spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: birthyear, birthday
            client-name: Naver
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: age_range, birthday
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/modi;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: filesystem:${MODI_ROOT}/src/main/resources/db/migration, filesystem:${MODI_ROOT}/src/main/resources/db/seed
    baseline-on-migrate: true
  output:
    ansi.enabled: always
  h2:
    console.enabled: true

jwt:
  issuer: modi
  client-secret: ${JWT_SECRET}
  expiry-seconds: 172800

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
