  # This is a basic workflow to help you get started with Actions

  name: CI

  # Controls when the workflow will run
  on:
    # Triggers the workflow on push or pull request events but only for the develop branch
    push:
      branches: [ develop ]
    pull_request:
      branches: [ develop ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  env:
    S3_BUCKET_NAME: modi-deploy

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      env:
        NAVER_CLIENT_ID : ${{ secrets.NAVER_CLIENT_ID }}
        NAVER_CLIENT_SECRET : ${{ secrets.NAVER_CLIENT_SECRET }}
        KAKAO_CLIENT_ID : ${{ secrets.KAKAO_CLIENT_ID }}
        KAKAO_CLIENT_SECRET : ${{ secrets.KAKAO_CLIENT_SECRET }}
        JWT_SECRET : ${{ secrets.JWT_SECRET }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        KMS_ARN: ${{ secrets.KMS_ARN }}


      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            token: ${{secrets.SUBMODULE_TOKEN}}
            submodules: true

        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11

        - name: Grant execute permission for gradlew
          run: chmod +x ./gradlew
          shell: bash

        - name: Build with Gradle
          run: ./gradlew build
          shell: bash
